name: nem2_crypto
description: Pure Dart crypto for ProximaX/NEM Catapult.
version: 1.0.3
homepage: https://github.com/proximax-storage/nem2-crypto-dart
author: Eleazar Garrido <eleazar.garrido@proximax.io>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  fixnum: ^0.10.9
  pointycastle: ^1.0.1
  hex: ^0.1.2

dev_dependencies:
  test: ^1.5.3
